# Utilisation de l'image de base ASP.NET 6.0 SDK pour le build
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copie des fichiers de l'application
COPY . .

# Restaurer les dépendances et exécuter les tests unitaires (environnement de développement)
RUN dotnet restore
RUN dotnet test TasksManagement_Tests/

# Construction de l'application
RUN dotnet publish -c Release -o out

# Environnement de production
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

# Environnement de développement
FROM build AS development
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 5001
ENTRYPOINT ["dotnet", "run", "--urls", "http://0.0.0.0:5001"]

# Environnement de staging pour les tests d'intégration
FROM build AS staging
ENV ASPNETCORE_ENVIRONMENT=Staging
# Ajouter les tests d'intégration ici
RUN dotnet test TasksManagement_TestsIntegrationSql/


# Environnement de production
FROM build AS production
ENV ASPNETCORE_ENVIRONMENT=Production
EXPOSE 80
ENTRYPOINT ["dotnet", "TasksManagement_API.dll"]
